Update YAML file definitions
layerml/examples pull request #44
Opened 2021-11-16 05:17 UTC by mwitiderrick

Update YAML files to reflect these changes https://linear.app/layer/issue/USR-351/change-how-layer-project-yaml-files-are-identified-as-being-of-a

2021-11-16 09:26 UTC, asantinc commented on titanic-spark/README.md
> +
@mwitiderrick this file seems to have changed a lot, and comments have been removed - is that intentional?

2021-11-16 09:34 UTC, asantinc requested changes
Thanks @mwitiderrick. 

A couple of comments:
- There's at least one model.yaml file that needs to be updated so that they have a `type: model` field - e.g. https://github.com/layerml/examples/blob/0210f8fb8331ad14e6bd32f4aa990fe620b1da26/cats-and-dogs-classification/models/model/cats_dogs_model.yaml - but there's probably others too
- one of the benefits of using the type field is that we no longer need to have separate directories for each of the entities (models, datasets, featuresets). Previously because all featuresets and datasets needed to be called `dataset.yaml` and all models had to be called `model.yaml`, we needed to create separate directories for each entity. Getting rid of this limitation was something that @buraklayer seemed excited about when I reviewed the spec that sparked this work (see comment https://www.notion.so/Consistent-Layer-Taxonomy-314a207e3eb24e07a980c4761d9a8a30?d=3993211b5a6049d9a947f0e450d3e9dd#762678e3b97e4c769741d68561ae2131) - are there any changes we can make to the example projects that take advantage of this?

2021-11-16 13:37 UTC, asantinc commented on cats-and-dogs-classification/data/dataset/cats_dogs_data.yaml
> +# Datasets are created by defining a .yaml with any name and adding type:dataset
@mwitiderrick I think you're missing word `file` after `.yaml`. Can we update to `# Models are created by defining a .yaml file with any name and adding type:dataset`. Same applies to other comments.

2021-11-16 13:38 UTC, asantinc commented on churn-prediction/data/event_log/event_log_data.yaml
> +# Datasets are created by defining  a .yaml with any name and adding type:dataset.
@mwitiderrick There's an extra space between the words `defining` and `a`

2021-11-16 13:38 UTC, asantinc commented on churn-prediction/data/event_log/event_log_data.yaml
> +# Datasets are created by defining  a .yaml with any name and adding type:dataset.
Same applies to other comments below

2021-11-16 13:39 UTC, asantinc commented on cats-and-dogs-classification/models/model/cats_dogs_model.yaml
> +# Models are created by defining  a .yaml with any name and adding type:model.
I would remove the final `.` in the comment, just to avoid confusion - we don't want the user adding a `.` at the end by mistake 😅

2021-11-16 13:42 UTC, asantinc commented on cats-and-dogs-classification/models/model/cats_dogs_model.yaml
> +# Models are created by defining  a .yaml with any name and adding type:model.
Also, we seem to follow the standard that special words such as `.yaml`, filenames, and code snippets such as `type: model` are surrounded by an apostrophe on both sides: ` -- I would make sure all comments you edited follow that pattern

2021-11-16 13:43 UTC, asantinc commented on titanic/models/survival_model/survival_model.yaml
> +#Models are created by defining  a .yaml with any name and adding type:model.
Missing space between # and Model

2021-11-16 15:44 UTC, mwitiderrick commented
@asantinc I am working on a new project, and I will see how to use these changes to improve the project structure

2021-11-17 10:15 UTC, asantinc approved these changes

2021-11-18 13:42 UTC, merged