change main readme file
layerml/examples pull request #45
Opened 2021-11-17 10:24 UTC by mwitiderrick

2021-11-17 16:15 UTC, oddlittlebird requested changes
While the changes themselves are okay, I think it would be better to keep this information in the user documentation, not the README, unless we can figure out a way to single source it. Otherwise, the two sets of instructions are likely to get out of sync very quickly.

A better solution is to link to the instructions in the docs (yes, the issue is on my To Do list) rather than list them here.

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +You can deploy your model by clicking the Deploy button next to the model on the model catalog.
```suggestion
You can deploy your model by clicking the Deploy button next to the model in the Model Catalog. 
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +## The model catalog
```suggestion
## Layer Model Catalog
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +The second link that was generated on the terminal takes you to the model catalog:
```suggestion
The second link that was generated on the terminal takes you to the Model Catalog:
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +## Run predictions on the deployed model
```suggestion

## Run predictions on the deployed model 
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +The API returns either a [0] or a [1], predicting whether that passenger survived.
```suggestion

The API returns either a [0] or a [1], predicting whether that passenger survived.
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +## Use the generated entities in a Jupyter Notebook
```suggestion

## Use the generated entities in a Jupyter Notebook
```

2021-11-17 16:15 UTC, oddlittlebird commented on README.md
> +Entities generated with Layer can also be accessed in a Jupyter Notebook. Layer allows you to access the datasets, featuresets and models.
```suggestion
Entities generated with Layer can also be accessed in a Jupyter Notebook. Layer allows you to access the datasets, feature sets, and models. 
```

2021-11-18 08:33 UTC, govu reviewed
We should provide links to docs, for example in the data catalog section, we can briefly talk about it but put a link so that people can read more about it

2021-11-23 06:26 UTC, mecevit approved these changes
I think we can somehow automate populating this data from the docs by single sourcing it later. But for now it's good to go. cc @oddlittlebird

2021-11-23 08:26 UTC, merged